name: Dataflow CI/CD with WIF

on:
  push:
    branches:
      - main

jobs:
  dataflow-job:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      id-token: write   # REQUIRED for WIF

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Authenticate to GCP (WIF)
        uses: google-github-actions/auth@v2
        with:
          workload_identity_provider: "projects/5848878514/locations/global/workloadIdentityPools/github-pool/providers/github-provider"
          service_account: "github-dataflow-sa@sandbox-explorer-490214.iam.gserviceaccount.com"

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v1

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install Python Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run Dataflow Job
        run: |
          python dataflow/wordcount.py \
            --runner=DataflowRunner \
            --project=sandbox-explorer-490214 \
            --region=us-central1 \
            --temp_location=gs://test-bucket-2015/temp \
            --staging_location=gs://test-bucket-2015/staging \
            --input=gs://test-bucket-2015/input/sample.txt \
            --output=gs://test-bucket-2015/output/result \
            --job_name=wordcount-$(date +%Y%m%d-%H%M%S)
